name: Run all notebooks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert
          pip install pandas

      - name: Run notebooks
        run: |
          jupyter nbconvert --to notebook --execute scripts/*.ipynb
      
      - name: Add and move generated files
        run: |
          git add scripts/*.csv
          git mv scripts/*.csv .
          working-directory: ${{ github.workspace }}
    
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.0
        with:
          file_pattern: '*.csv'
          commit_message: 'Rerun notebooks and update generated files'
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.ACCESS_TOKEN }}
            branch: test_action

